/*
SQLyog - Free MySQL GUI v5.11
Host - 5.5.13 : Database - tablacalorias
*********************************************************************
Server version : 5.5.13
*/

SET NAMES utf8;

SET SQL_MODE='';

create database if not exists `tablacalorias`;

USE `tablacalorias`;

/*Table structure for table `comida` */

DROP TABLE IF EXISTS `comida`;

CREATE TABLE `comida` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nombre` varchar(50) DEFAULT NULL,
  `calorias` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=367 DEFAULT CHARSET=latin1;

/*Data for the table `comida` */

insert into `comida` (`id`,`nombre`,`calorias`) values (1,'aceite de girasol',900);
insert into `comida` (`id`,`nombre`,`calorias`) values (2,'aceite de maíz',900);
insert into `comida` (`id`,`nombre`,`calorias`) values (3,'aceite de maní',900);
insert into `comida` (`id`,`nombre`,`calorias`) values (4,'aceite de oliva',900);
insert into `comida` (`id`,`nombre`,`calorias`) values (5,'aceite de soja',900);
insert into `comida` (`id`,`nombre`,`calorias`) values (6,'aceitunas negras',349);
insert into `comida` (`id`,`nombre`,`calorias`) values (7,'aceitunas verdes',132);
insert into `comida` (`id`,`nombre`,`calorias`) values (8,'acelgas',33);
insert into `comida` (`id`,`nombre`,`calorias`) values (9,'agua ardiente',280);
insert into `comida` (`id`,`nombre`,`calorias`) values (10,'agua tónica',34);
insert into `comida` (`id`,`nombre`,`calorias`) values (11,'ajos',169);
insert into `comida` (`id`,`nombre`,`calorias`) values (12,'alcachofas',64);
insert into `comida` (`id`,`nombre`,`calorias`) values (13,'almejas',50);
insert into `comida` (`id`,`nombre`,`calorias`) values (14,'almendras',620);
insert into `comida` (`id`,`nombre`,`calorias`) values (15,'anchoas',175);
insert into `comida` (`id`,`nombre`,`calorias`) values (16,'anguilas',200);
insert into `comida` (`id`,`nombre`,`calorias`) values (17,'anís',312);
insert into `comida` (`id`,`nombre`,`calorias`) values (18,'apio',20);
insert into `comida` (`id`,`nombre`,`calorias`) values (19,'arándanos',41);
insert into `comida` (`id`,`nombre`,`calorias`) values (20,'arenque ahumado',209);
insert into `comida` (`id`,`nombre`,`calorias`) values (21,'arenque seco',122);
insert into `comida` (`id`,`nombre`,`calorias`) values (22,'arroz blanco',354);
insert into `comida` (`id`,`nombre`,`calorias`) values (23,'arroz con leche',123);
insert into `comida` (`id`,`nombre`,`calorias`) values (24,'arroz integral',350);
insert into `comida` (`id`,`nombre`,`calorias`) values (25,'arvejas',78);
insert into `comida` (`id`,`nombre`,`calorias`) values (26,'arvejas congeladas',71);
insert into `comida` (`id`,`nombre`,`calorias`) values (27,'arvejas secas',340);
insert into `comida` (`id`,`nombre`,`calorias`) values (28,'atún en lata con aceite vegetal',280);
insert into `comida` (`id`,`nombre`,`calorias`) values (29,'atún en lata con agua',127);
insert into `comida` (`id`,`nombre`,`calorias`) values (30,'atún fresco',225);
insert into `comida` (`id`,`nombre`,`calorias`) values (31,'avellanas',675);
insert into `comida` (`id`,`nombre`,`calorias`) values (32,'avena',367);
insert into `comida` (`id`,`nombre`,`calorias`) values (33,'azúcar',380);
insert into `comida` (`id`,`nombre`,`calorias`) values (34,'babaroise',149);
insert into `comida` (`id`,`nombre`,`calorias`) values (35,'bacalao fresco',74);
insert into `comida` (`id`,`nombre`,`calorias`) values (36,'bacalao salado remojado',108);
insert into `comida` (`id`,`nombre`,`calorias`) values (37,'bacalao seco',322);
insert into `comida` (`id`,`nombre`,`calorias`) values (38,'bacon',665);
insert into `comida` (`id`,`nombre`,`calorias`) values (39,'barra de chocolate',441);
insert into `comida` (`id`,`nombre`,`calorias`) values (40,'batido lácteo de cacao',100);
insert into `comida` (`id`,`nombre`,`calorias`) values (41,'bechamel',115);
insert into `comida` (`id`,`nombre`,`calorias`) values (42,'berenjena',29);
insert into `comida` (`id`,`nombre`,`calorias`) values (43,'berlín',588);
insert into `comida` (`id`,`nombre`,`calorias`) values (44,'berros',21);
insert into `comida` (`id`,`nombre`,`calorias`) values (45,'besugo',118);
insert into `comida` (`id`,`nombre`,`calorias`) values (46,'bizcocho',456);
insert into `comida` (`id`,`nombre`,`calorias`) values (47,'brazo de reina',150);
insert into `comida` (`id`,`nombre`,`calorias`) values (48,'brócoli',31);
insert into `comida` (`id`,`nombre`,`calorias`) values (49,'buñuelos',123);
insert into `comida` (`id`,`nombre`,`calorias`) values (50,'butifarra cocida',390);
insert into `comida` (`id`,`nombre`,`calorias`) values (51,'butifarra, salchicha fresca',326);
insert into `comida` (`id`,`nombre`,`calorias`) values (52,'caballa',153);
insert into `comida` (`id`,`nombre`,`calorias`) values (53,'cabrito',127);
insert into `comida` (`id`,`nombre`,`calorias`) values (54,'cacao en polvo con azúcar instantáneo',366);
insert into `comida` (`id`,`nombre`,`calorias`) values (55,'cacao en polvo sin azúcar a la taza',439);
insert into `comida` (`id`,`nombre`,`calorias`) values (56,'café',1);
insert into `comida` (`id`,`nombre`,`calorias`) values (57,'calabacín',31);
insert into `comida` (`id`,`nombre`,`calorias`) values (58,'calabaza',24);
insert into `comida` (`id`,`nombre`,`calorias`) values (59,'calamar',82);
insert into `comida` (`id`,`nombre`,`calorias`) values (60,'caldos concentrados',259);
insert into `comida` (`id`,`nombre`,`calorias`) values (61,'canapé',234);
insert into `comida` (`id`,`nombre`,`calorias`) values (62,'canelones',127);
insert into `comida` (`id`,`nombre`,`calorias`) values (63,'cangrejo',85);
insert into `comida` (`id`,`nombre`,`calorias`) values (64,'caqui',64);
insert into `comida` (`id`,`nombre`,`calorias`) values (65,'caramelos',378);
insert into `comida` (`id`,`nombre`,`calorias`) values (66,'castañas',199);
insert into `comida` (`id`,`nombre`,`calorias`) values (67,'caviar',233);
insert into `comida` (`id`,`nombre`,`calorias`) values (68,'cebada',373);
insert into `comida` (`id`,`nombre`,`calorias`) values (69,'cebolla',47);
insert into `comida` (`id`,`nombre`,`calorias`) values (70,'cebolla tierna',39);
insert into `comida` (`id`,`nombre`,`calorias`) values (71,'centeno',350);
insert into `comida` (`id`,`nombre`,`calorias`) values (72,'cerdo, chuleta',330);
insert into `comida` (`id`,`nombre`,`calorias`) values (73,'cerdo, hígado',153);
insert into `comida` (`id`,`nombre`,`calorias`) values (74,'cerdo, lomo',208);
insert into `comida` (`id`,`nombre`,`calorias`) values (75,'cereales con chocolate',358);
insert into `comida` (`id`,`nombre`,`calorias`) values (76,'cereales desayuno, con miel',386);
insert into `comida` (`id`,`nombre`,`calorias`) values (77,'cereza',47);
insert into `comida` (`id`,`nombre`,`calorias`) values (78,'cerveza negra',37);
insert into `comida` (`id`,`nombre`,`calorias`) values (79,'cerveza rubia',45);
insert into `comida` (`id`,`nombre`,`calorias`) values (80,'champaña demi-sec',90);
insert into `comida` (`id`,`nombre`,`calorias`) values (81,'champaña dulce',118);
insert into `comida` (`id`,`nombre`,`calorias`) values (82,'champaña seca',85);
insert into `comida` (`id`,`nombre`,`calorias`) values (83,'champiñón y otras cetas',28);
insert into `comida` (`id`,`nombre`,`calorias`) values (84,'charqui',110);
insert into `comida` (`id`,`nombre`,`calorias`) values (85,'chicharrón',601);
insert into `comida` (`id`,`nombre`,`calorias`) values (86,'chirimoya',78);
insert into `comida` (`id`,`nombre`,`calorias`) values (87,'choclo',96);
insert into `comida` (`id`,`nombre`,`calorias`) values (88,'chocolate con leche',550);
insert into `comida` (`id`,`nombre`,`calorias`) values (89,'chocolate sin leche',530);
insert into `comida` (`id`,`nombre`,`calorias`) values (90,'chorizo',468);
insert into `comida` (`id`,`nombre`,`calorias`) values (91,'churros',348);
insert into `comida` (`id`,`nombre`,`calorias`) values (92,'ciervo',120);
insert into `comida` (`id`,`nombre`,`calorias`) values (93,'ciruela',44);
insert into `comida` (`id`,`nombre`,`calorias`) values (94,'ciruela seca',290);
insert into `comida` (`id`,`nombre`,`calorias`) values (95,'clara',48);
insert into `comida` (`id`,`nombre`,`calorias`) values (96,'cochayuyo',50);
insert into `comida` (`id`,`nombre`,`calorias`) values (97,'coco',646);
insert into `comida` (`id`,`nombre`,`calorias`) values (98,'codorniz y perdiz',114);
insert into `comida` (`id`,`nombre`,`calorias`) values (99,'col',28);
insert into `comida` (`id`,`nombre`,`calorias`) values (100,'col de bruselas',54);
insert into `comida` (`id`,`nombre`,`calorias`) values (101,'coliflor',30);
insert into `comida` (`id`,`nombre`,`calorias`) values (102,'compota de frutas',90);
insert into `comida` (`id`,`nombre`,`calorias`) values (103,'conejo, liebre',162);
insert into `comida` (`id`,`nombre`,`calorias`) values (104,'congrio',112);
insert into `comida` (`id`,`nombre`,`calorias`) values (105,'coñac, brandy',243);
insert into `comida` (`id`,`nombre`,`calorias`) values (106,'copos de maíz',350);
insert into `comida` (`id`,`nombre`,`calorias`) values (107,'cordero lechón',105);
insert into `comida` (`id`,`nombre`,`calorias`) values (108,'cordero pierna',98);
insert into `comida` (`id`,`nombre`,`calorias`) values (109,'cordero, costillas',215);
insert into `comida` (`id`,`nombre`,`calorias`) values (110,'cordero, hígado',132);
insert into `comida` (`id`,`nombre`,`calorias`) values (111,'crema chocolate con avellanas',549);
insert into `comida` (`id`,`nombre`,`calorias`) values (112,'crema de cacao',260);
insert into `comida` (`id`,`nombre`,`calorias`) values (113,'croissant chocolate',469);
insert into `comida` (`id`,`nombre`,`calorias`) values (114,'croissant, donut',456);
insert into `comida` (`id`,`nombre`,`calorias`) values (115,'croquetas',123);
insert into `comida` (`id`,`nombre`,`calorias`) values (116,'cuajada',92);
insert into `comida` (`id`,`nombre`,`calorias`) values (117,'daiquiri',122);
insert into `comida` (`id`,`nombre`,`calorias`) values (118,'damasco',44);
insert into `comida` (`id`,`nombre`,`calorias`) values (119,'dátil',279);
insert into `comida` (`id`,`nombre`,`calorias`) values (120,'dátil seco',306);
insert into `comida` (`id`,`nombre`,`calorias`) values (121,'dorada',80);
insert into `comida` (`id`,`nombre`,`calorias`) values (122,'dulce de membrillo',215);
insert into `comida` (`id`,`nombre`,`calorias`) values (123,'durazno',52);
insert into `comida` (`id`,`nombre`,`calorias`) values (124,'durazno en almíbar',84);
insert into `comida` (`id`,`nombre`,`calorias`) values (125,'durazno en conserva',79);
insert into `comida` (`id`,`nombre`,`calorias`) values (126,'empanada de atún',243);
insert into `comida` (`id`,`nombre`,`calorias`) values (127,'endibia',22);
insert into `comida` (`id`,`nombre`,`calorias`) values (128,'escarola',37);
insert into `comida` (`id`,`nombre`,`calorias`) values (129,'espárragos',26);
insert into `comida` (`id`,`nombre`,`calorias`) values (130,'espárragos en lata',24);
insert into `comida` (`id`,`nombre`,`calorias`) values (131,'espinaca',32);
insert into `comida` (`id`,`nombre`,`calorias`) values (132,'espinacas congeladas',25);
insert into `comida` (`id`,`nombre`,`calorias`) values (133,'faisán',144);
insert into `comida` (`id`,`nombre`,`calorias`) values (134,'flan de huevo',126);
insert into `comida` (`id`,`nombre`,`calorias`) values (135,'flan de vainilla',102);
insert into `comida` (`id`,`nombre`,`calorias`) values (136,'foie-gras',518);
insert into `comida` (`id`,`nombre`,`calorias`) values (137,'frambuesa',40);
insert into `comida` (`id`,`nombre`,`calorias`) values (138,'fresas',36);
insert into `comida` (`id`,`nombre`,`calorias`) values (139,'galletas de chocolate',524);
insert into `comida` (`id`,`nombre`,`calorias`) values (140,'galletas de mantequilla',397);
insert into `comida` (`id`,`nombre`,`calorias`) values (141,'galletas saladas',464);
insert into `comida` (`id`,`nombre`,`calorias`) values (142,'gallina',369);
insert into `comida` (`id`,`nombre`,`calorias`) values (143,'gallo',73);
insert into `comida` (`id`,`nombre`,`calorias`) values (144,'gambas',96);
insert into `comida` (`id`,`nombre`,`calorias`) values (145,'garbanzos',361);
insert into `comida` (`id`,`nombre`,`calorias`) values (146,'gin y tónica',76);
insert into `comida` (`id`,`nombre`,`calorias`) values (147,'ginebra',244);
insert into `comida` (`id`,`nombre`,`calorias`) values (148,'gomas de fruta',172);
insert into `comida` (`id`,`nombre`,`calorias`) values (149,'granada',65);
insert into `comida` (`id`,`nombre`,`calorias`) values (150,'grosella',37);
insert into `comida` (`id`,`nombre`,`calorias`) values (151,'habas secas',343);
insert into `comida` (`id`,`nombre`,`calorias`) values (152,'habas tiernas',64);
insert into `comida` (`id`,`nombre`,`calorias`) values (153,'hamburguesa',230);
insert into `comida` (`id`,`nombre`,`calorias`) values (154,'harina de maíz',349);
insert into `comida` (`id`,`nombre`,`calorias`) values (155,'harina de trigo integral',340);
insert into `comida` (`id`,`nombre`,`calorias`) values (156,'harina de trigo refinada',353);
insert into `comida` (`id`,`nombre`,`calorias`) values (157,'helados de agua',139);
insert into `comida` (`id`,`nombre`,`calorias`) values (158,'helados lácteos',167);
insert into `comida` (`id`,`nombre`,`calorias`) values (159,'higos',80);
insert into `comida` (`id`,`nombre`,`calorias`) values (160,'higos secos',275);
insert into `comida` (`id`,`nombre`,`calorias`) values (161,'hinojo',16);
insert into `comida` (`id`,`nombre`,`calorias`) values (162,'huevo duro',147);
insert into `comida` (`id`,`nombre`,`calorias`) values (163,'huevo entero',162);
insert into `comida` (`id`,`nombre`,`calorias`) values (164,'jabalí',107);
insert into `comida` (`id`,`nombre`,`calorias`) values (165,'jalea sola',30);
insert into `comida` (`id`,`nombre`,`calorias`) values (166,'jamón',380);
insert into `comida` (`id`,`nombre`,`calorias`) values (167,'jamón cocido',126);
insert into `comida` (`id`,`nombre`,`calorias`) values (168,'jamón crudo',296);
insert into `comida` (`id`,`nombre`,`calorias`) values (169,'jamón y queso apanados',214);
insert into `comida` (`id`,`nombre`,`calorias`) values (170,'jamón york',289);
insert into `comida` (`id`,`nombre`,`calorias`) values (171,'kani-kama',80);
insert into `comida` (`id`,`nombre`,`calorias`) values (172,'ketchup',98);
insert into `comida` (`id`,`nombre`,`calorias`) values (173,'kiwi',51);
insert into `comida` (`id`,`nombre`,`calorias`) values (174,'langosta',67);
insert into `comida` (`id`,`nombre`,`calorias`) values (175,'langostino',96);
insert into `comida` (`id`,`nombre`,`calorias`) values (176,'lasaña',147);
insert into `comida` (`id`,`nombre`,`calorias`) values (177,'leche asada',145);
insert into `comida` (`id`,`nombre`,`calorias`) values (178,'leche condensada c/azúcar',350);
insert into `comida` (`id`,`nombre`,`calorias`) values (179,'leche condensada s/azúcar',160);
insert into `comida` (`id`,`nombre`,`calorias`) values (180,'leche de almendras',335);
insert into `comida` (`id`,`nombre`,`calorias`) values (181,'leche de cabra',72);
insert into `comida` (`id`,`nombre`,`calorias`) values (182,'leche de oveja',96);
insert into `comida` (`id`,`nombre`,`calorias`) values (183,'leche descremada',36);
insert into `comida` (`id`,`nombre`,`calorias`) values (184,'leche en polvo descremada',373);
insert into `comida` (`id`,`nombre`,`calorias`) values (185,'leche en polvo entera',500);
insert into `comida` (`id`,`nombre`,`calorias`) values (186,'leche entera',68);
insert into `comida` (`id`,`nombre`,`calorias`) values (187,'leche nevada',120);
insert into `comida` (`id`,`nombre`,`calorias`) values (188,'leche semi descremada',49);
insert into `comida` (`id`,`nombre`,`calorias`) values (189,'lechuga',18);
insert into `comida` (`id`,`nombre`,`calorias`) values (190,'lengua de vaca',191);
insert into `comida` (`id`,`nombre`,`calorias`) values (191,'lenguado',73);
insert into `comida` (`id`,`nombre`,`calorias`) values (192,'lentejas',336);
insert into `comida` (`id`,`nombre`,`calorias`) values (193,'licor de caña',273);
insert into `comida` (`id`,`nombre`,`calorias`) values (194,'limón',39);
insert into `comida` (`id`,`nombre`,`calorias`) values (195,'lomo embuchado',380);
insert into `comida` (`id`,`nombre`,`calorias`) values (196,'lubina',118);
insert into `comida` (`id`,`nombre`,`calorias`) values (197,'lucio',81);
insert into `comida` (`id`,`nombre`,`calorias`) values (198,'magdalenas',469);
insert into `comida` (`id`,`nombre`,`calorias`) values (199,'maíz dulce en conserva',50);
insert into `comida` (`id`,`nombre`,`calorias`) values (200,'maíz, palomitas',592);
insert into `comida` (`id`,`nombre`,`calorias`) values (201,'maíz, tiras fritas',459);
insert into `comida` (`id`,`nombre`,`calorias`) values (202,'mandarina',40);
insert into `comida` (`id`,`nombre`,`calorias`) values (203,'mango',57);
insert into `comida` (`id`,`nombre`,`calorias`) values (204,'maní',560);
insert into `comida` (`id`,`nombre`,`calorias`) values (205,'manteca',670);
insert into `comida` (`id`,`nombre`,`calorias`) values (206,'mantequilla',752);
insert into `comida` (`id`,`nombre`,`calorias`) values (207,'manzana',52);
insert into `comida` (`id`,`nombre`,`calorias`) values (208,'manzana asada',157);
insert into `comida` (`id`,`nombre`,`calorias`) values (209,'margarina vegetal',752);
insert into `comida` (`id`,`nombre`,`calorias`) values (210,'mayonesa',718);
insert into `comida` (`id`,`nombre`,`calorias`) values (211,'mayonesa light',374);
insert into `comida` (`id`,`nombre`,`calorias`) values (212,'mejillón',74);
insert into `comida` (`id`,`nombre`,`calorias`) values (213,'melón',31);
insert into `comida` (`id`,`nombre`,`calorias`) values (214,'merluza',86);
insert into `comida` (`id`,`nombre`,`calorias`) values (215,'mermeladas con azúcar',280);
insert into `comida` (`id`,`nombre`,`calorias`) values (216,'mermeladas sin azúcar	',145);
insert into `comida` (`id`,`nombre`,`calorias`) values (217,'mero',118);
insert into `comida` (`id`,`nombre`,`calorias`) values (218,'miel',300);
insert into `comida` (`id`,`nombre`,`calorias`) values (219,'mora',37);
insert into `comida` (`id`,`nombre`,`calorias`) values (220,'mortadela',265);
insert into `comida` (`id`,`nombre`,`calorias`) values (221,'mostaza',15);
insert into `comida` (`id`,`nombre`,`calorias`) values (222,'mote con huesillos',221);
insert into `comida` (`id`,`nombre`,`calorias`) values (223,'mousse',177);
insert into `comida` (`id`,`nombre`,`calorias`) values (224,'nabos',29);
insert into `comida` (`id`,`nombre`,`calorias`) values (225,'naranja',44);
insert into `comida` (`id`,`nombre`,`calorias`) values (226,'nata o crema de leche',298);
insert into `comida` (`id`,`nombre`,`calorias`) values (227,'nectarina',64);
insert into `comida` (`id`,`nombre`,`calorias`) values (228,'nísperos',97);
insert into `comida` (`id`,`nombre`,`calorias`) values (229,'nueces',660);
insert into `comida` (`id`,`nombre`,`calorias`) values (230,'ñoquis de papa',246);
insert into `comida` (`id`,`nombre`,`calorias`) values (231,'ostras',80);
insert into `comida` (`id`,`nombre`,`calorias`) values (232,'palta',167);
insert into `comida` (`id`,`nombre`,`calorias`) values (233,'pan de centeno',241);
insert into `comida` (`id`,`nombre`,`calorias`) values (234,'pan de trigo blanco',255);
insert into `comida` (`id`,`nombre`,`calorias`) values (235,'pan de trigo integral',239);
insert into `comida` (`id`,`nombre`,`calorias`) values (236,'pan de trigo molde blanco',233);
insert into `comida` (`id`,`nombre`,`calorias`) values (237,'pan de trigo molde integral',216);
insert into `comida` (`id`,`nombre`,`calorias`) values (238,'panqueque con manjar',219);
insert into `comida` (`id`,`nombre`,`calorias`) values (239,'papas cocidas',86);
insert into `comida` (`id`,`nombre`,`calorias`) values (240,'papas fritas',544);
insert into `comida` (`id`,`nombre`,`calorias`) values (241,'papaya',45);
insert into `comida` (`id`,`nombre`,`calorias`) values (242,'pasta al huevo',368);
insert into `comida` (`id`,`nombre`,`calorias`) values (243,'pasta de hojaldre cocida',565);
insert into `comida` (`id`,`nombre`,`calorias`) values (244,'pasta de sémola',361);
insert into `comida` (`id`,`nombre`,`calorias`) values (245,'pastel de manzana',311);
insert into `comida` (`id`,`nombre`,`calorias`) values (246,'pastel de manzana, masa hojaldre',456);
insert into `comida` (`id`,`nombre`,`calorias`) values (247,'pastel de queso',414);
insert into `comida` (`id`,`nombre`,`calorias`) values (248,'pato',200);
insert into `comida` (`id`,`nombre`,`calorias`) values (249,'pavo, muslo',186);
insert into `comida` (`id`,`nombre`,`calorias`) values (250,'pavo, pechuga',134);
insert into `comida` (`id`,`nombre`,`calorias`) values (251,'pejerrey',87);
insert into `comida` (`id`,`nombre`,`calorias`) values (252,'pepino',12);
insert into `comida` (`id`,`nombre`,`calorias`) values (253,'pera',61);
insert into `comida` (`id`,`nombre`,`calorias`) values (254,'perdiz',120);
insert into `comida` (`id`,`nombre`,`calorias`) values (255,'perejil',55);
insert into `comida` (`id`,`nombre`,`calorias`) values (256,'pescado apanado',178);
insert into `comida` (`id`,`nombre`,`calorias`) values (257,'pez espada',109);
insert into `comida` (`id`,`nombre`,`calorias`) values (258,'pie de limón',298);
insert into `comida` (`id`,`nombre`,`calorias`) values (259,'pies de cerdo',290);
insert into `comida` (`id`,`nombre`,`calorias`) values (260,'pimiento',22);
insert into `comida` (`id`,`nombre`,`calorias`) values (261,'piña',51);
insert into `comida` (`id`,`nombre`,`calorias`) values (262,'piña colada',194);
insert into `comida` (`id`,`nombre`,`calorias`) values (263,'piña en almíbar',84);
insert into `comida` (`id`,`nombre`,`calorias`) values (264,'piñones',660);
insert into `comida` (`id`,`nombre`,`calorias`) values (265,'pisco',210);
insert into `comida` (`id`,`nombre`,`calorias`) values (266,'pistacho',581);
insert into `comida` (`id`,`nombre`,`calorias`) values (267,'pizza',234);
insert into `comida` (`id`,`nombre`,`calorias`) values (268,'plátano',90);
insert into `comida` (`id`,`nombre`,`calorias`) values (269,'polenta',358);
insert into `comida` (`id`,`nombre`,`calorias`) values (270,'pollo apanado',283);
insert into `comida` (`id`,`nombre`,`calorias`) values (271,'pollo, hígado',129);
insert into `comida` (`id`,`nombre`,`calorias`) values (272,'pollo, muslo',186);
insert into `comida` (`id`,`nombre`,`calorias`) values (273,'pollo, pechuga',134);
insert into `comida` (`id`,`nombre`,`calorias`) values (274,'pomelo',30);
insert into `comida` (`id`,`nombre`,`calorias`) values (275,'poroto',316);
insert into `comida` (`id`,`nombre`,`calorias`) values (276,'porotos verdes',21);
insert into `comida` (`id`,`nombre`,`calorias`) values (277,'puerros',42);
insert into `comida` (`id`,`nombre`,`calorias`) values (278,'pulpo',57);
insert into `comida` (`id`,`nombre`,`calorias`) values (279,'puré de papas',357);
insert into `comida` (`id`,`nombre`,`calorias`) values (280,'queso blanco desnatado',70);
insert into `comida` (`id`,`nombre`,`calorias`) values (281,'queso brie',263);
insert into `comida` (`id`,`nombre`,`calorias`) values (282,'queso cammembert',312);
insert into `comida` (`id`,`nombre`,`calorias`) values (283,'queso cheddar',381);
insert into `comida` (`id`,`nombre`,`calorias`) values (284,'queso crema',245);
insert into `comida` (`id`,`nombre`,`calorias`) values (285,'queso de bola',349);
insert into `comida` (`id`,`nombre`,`calorias`) values (286,'queso de burgos',174);
insert into `comida` (`id`,`nombre`,`calorias`) values (287,'queso de oveja',245);
insert into `comida` (`id`,`nombre`,`calorias`) values (288,'queso edam',306);
insert into `comida` (`id`,`nombre`,`calorias`) values (289,'queso emmental',415);
insert into `comida` (`id`,`nombre`,`calorias`) values (290,'queso fundido untable',285);
insert into `comida` (`id`,`nombre`,`calorias`) values (291,'queso gruyere',391);
insert into `comida` (`id`,`nombre`,`calorias`) values (292,'queso manchego',376);
insert into `comida` (`id`,`nombre`,`calorias`) values (293,'queso mozzarella',245);
insert into `comida` (`id`,`nombre`,`calorias`) values (294,'queso parmesano',393);
insert into `comida` (`id`,`nombre`,`calorias`) values (295,'queso ricota',400);
insert into `comida` (`id`,`nombre`,`calorias`) values (296,'queso roquefort',405);
insert into `comida` (`id`,`nombre`,`calorias`) values (297,'rábanos',20);
insert into `comida` (`id`,`nombre`,`calorias`) values (298,'ravioles de carne y jamón',253);
insert into `comida` (`id`,`nombre`,`calorias`) values (299,'refrescos carbonatados',48);
insert into `comida` (`id`,`nombre`,`calorias`) values (300,'remolacha',40);
insert into `comida` (`id`,`nombre`,`calorias`) values (301,'repollo',19);
insert into `comida` (`id`,`nombre`,`calorias`) values (302,'requesón',96);
insert into `comida` (`id`,`nombre`,`calorias`) values (303,'rodaballo',81);
insert into `comida` (`id`,`nombre`,`calorias`) values (304,'rollos primavera',258);
insert into `comida` (`id`,`nombre`,`calorias`) values (305,'ron',244);
insert into `comida` (`id`,`nombre`,`calorias`) values (306,'rúcula',37);
insert into `comida` (`id`,`nombre`,`calorias`) values (307,'salamín',325);
insert into `comida` (`id`,`nombre`,`calorias`) values (308,'salchicha frankfurt',315);
insert into `comida` (`id`,`nombre`,`calorias`) values (309,'salchichón',294);
insert into `comida` (`id`,`nombre`,`calorias`) values (310,'salmón',172);
insert into `comida` (`id`,`nombre`,`calorias`) values (311,'salmón ahumado',154);
insert into `comida` (`id`,`nombre`,`calorias`) values (312,'salmonete',97);
insert into `comida` (`id`,`nombre`,`calorias`) values (313,'salsa de soja',61);
insert into `comida` (`id`,`nombre`,`calorias`) values (314,'salsa de tomate en conserva',86);
insert into `comida` (`id`,`nombre`,`calorias`) values (315,'salsa golf',640);
insert into `comida` (`id`,`nombre`,`calorias`) values (316,'sandía',30);
insert into `comida` (`id`,`nombre`,`calorias`) values (317,'sardina en lata con aceite vegetal',192);
insert into `comida` (`id`,`nombre`,`calorias`) values (318,'sardinas',151);
insert into `comida` (`id`,`nombre`,`calorias`) values (319,'sémola con leche',130);
insert into `comida` (`id`,`nombre`,`calorias`) values (320,'sémola de trigo',368);
insert into `comida` (`id`,`nombre`,`calorias`) values (321,'sidra dulce',33);
insert into `comida` (`id`,`nombre`,`calorias`) values (322,'sidra seca',35);
insert into `comida` (`id`,`nombre`,`calorias`) values (323,'sofrito',116);
insert into `comida` (`id`,`nombre`,`calorias`) values (324,'soja en grano',422);
insert into `comida` (`id`,`nombre`,`calorias`) values (325,'soja, brotes de',50);
insert into `comida` (`id`,`nombre`,`calorias`) values (326,'sopaipillas',190);
insert into `comida` (`id`,`nombre`,`calorias`) values (327,'sopas de sobre',49);
insert into `comida` (`id`,`nombre`,`calorias`) values (328,'té',1);
insert into `comida` (`id`,`nombre`,`calorias`) values (329,'ternera, bistec',181);
insert into `comida` (`id`,`nombre`,`calorias`) values (330,'ternera, chuleta',168);
insert into `comida` (`id`,`nombre`,`calorias`) values (331,'ternera, hígado',140);
insert into `comida` (`id`,`nombre`,`calorias`) values (332,'ternera, lengua',207);
insert into `comida` (`id`,`nombre`,`calorias`) values (333,'ternera, riñón',86);
insert into `comida` (`id`,`nombre`,`calorias`) values (334,'ternera, sesos',125);
insert into `comida` (`id`,`nombre`,`calorias`) values (335,'ternera, solomillo',290);
insert into `comida` (`id`,`nombre`,`calorias`) values (336,'tira de asado',401);
insert into `comida` (`id`,`nombre`,`calorias`) values (337,'tomate triturado en conserva',39);
insert into `comida` (`id`,`nombre`,`calorias`) values (338,'tomates',22);
insert into `comida` (`id`,`nombre`,`calorias`) values (339,'torta mil hojas',379);
insert into `comida` (`id`,`nombre`,`calorias`) values (340,'tortilla de papa',194);
insert into `comida` (`id`,`nombre`,`calorias`) values (341,'tripas',100);
insert into `comida` (`id`,`nombre`,`calorias`) values (342,'trucha',94);
insert into `comida` (`id`,`nombre`,`calorias`) values (343,'trufa',92);
insert into `comida` (`id`,`nombre`,`calorias`) values (344,'tutti fruti',185);
insert into `comida` (`id`,`nombre`,`calorias`) values (345,'uva',81);
insert into `comida` (`id`,`nombre`,`calorias`) values (346,'uva pasa',324);
insert into `comida` (`id`,`nombre`,`calorias`) values (347,'vacuno, hígado',129);
insert into `comida` (`id`,`nombre`,`calorias`) values (348,'vermouth amargo',112);
insert into `comida` (`id`,`nombre`,`calorias`) values (349,'vermouth dulce',160);
insert into `comida` (`id`,`nombre`,`calorias`) values (350,'vinagres',8);
insert into `comida` (`id`,`nombre`,`calorias`) values (351,'vino de mesa',70);
insert into `comida` (`id`,`nombre`,`calorias`) values (352,'vino dulce, jerez',160);
insert into `comida` (`id`,`nombre`,`calorias`) values (353,'vino oporto',160);
insert into `comida` (`id`,`nombre`,`calorias`) values (354,'vodka',315);
insert into `comida` (`id`,`nombre`,`calorias`) values (355,'whisky',244);
insert into `comida` (`id`,`nombre`,`calorias`) values (356,'yema',368);
insert into `comida` (`id`,`nombre`,`calorias`) values (357,'yogur desnatado',45);
insert into `comida` (`id`,`nombre`,`calorias`) values (358,'yogur desnatado con frutas',82);
insert into `comida` (`id`,`nombre`,`calorias`) values (359,'yogur natural',62);
insert into `comida` (`id`,`nombre`,`calorias`) values (360,'yogur natural con fruta',100);
insert into `comida` (`id`,`nombre`,`calorias`) values (361,'yuca',338);
insert into `comida` (`id`,`nombre`,`calorias`) values (362,'zanahoria',42);
insert into `comida` (`id`,`nombre`,`calorias`) values (363,'zumo de fruta',45);
insert into `comida` (`id`,`nombre`,`calorias`) values (364,'zumo de naranja',42);
insert into `comida` (`id`,`nombre`,`calorias`) values (365,'zumo de tomate',21);
